### ISSUE TITLE
Clarify semantic of array element assert containing subexpression ".[1]"

### ISSUE THREAD

**Issue by mbeckerle** [OpenGridForum/DFDL#26]
Erratum needed to state which this is equivalent to "../a[1]" or "../a[dfdl:occursIndex()]"

See minutes of call previous to 2021-10-14.

**Comment by mbeckerle** [comment]
Email discussion thread - messages with title "Clarification needed " .[1] " expression on an array element" dated 2021-06-29 and 2021-06-30 suggest the right choice is that .[1] on an array element means ../a[dfdl:occursIndex()] - that is. "." is not a reference to an array as a whole, but to a single scalar value within an array.

**Comment by mbeckerle** [comment]
Reviewed on call 2022-10-06.

No change in conclusion. .[1] means the element itself, not the first element of the current array.

**Comment by smhdfdl** [comment]
Mike not sure how to parse your sentence in comment https://github.com/OpenGridForum/DFDL/issues/26#issuecomment-1270261719.

**Comment by mbeckerle** [comment]
Updated the original comment to: Erratum needed to state which this is equivalent to "../a[1]" or "../a[dfdl:occursIndex()]"

Those are alternative interpretations.

Your most recent comment above raises another issue however. What is the value of `dfdl:occursIndex()` if we are in the second "a" array in the schema below:

```
<element name="a" type="xs:string" maxOccurs="unbounded"/>
<elemetn name="b" ... />
<element name="a" type="xs:string" maxOccurs="unbounded"/>
```
In that case `.[1]` meaning the same thing as `../a[dfdl:occursIndex()]` is still a bit unclear. 

I guess a further clarification about what indexes dfdl:occursIndex() varies over, is needed. I think for XPath consistency it has to vary with the XPath index, i.e., `../a[dfdl:occursIndex()]` must be equivalent to just `.` (dot, i.e., this element).

**Comment by mbeckerle** [comment]
On call 2022-11-03 mentioned that ../a[1] is problematic if there are multiple element children named 'a'. If there is no UPA error there is still the question of this always from the XPath perspective wanting to return the first element of the first 'a' child element.

**Comment by mbeckerle** [comment]
Using XPath online evaluator https://www.freeformatter.com/xpath-tester.html
with data like:
```
<root>
  <bar>1</bar>
  <bar>2</bar>
<foo/>
  <bar>3</bar>
  <bar>4</bar>
</root>
```
and paths like
`fn:head(/root/bar)/.[1]`

**Comment by mbeckerle** [comment]
When a relative path expression "." is used and evaluated when parsing or unparsing there is always a "context node" which is an individual node. If that node is from an array element, then one must consider the node as identified by a path expression that contains a specific array index for every array path step on the path, including the final one, so that only a single array element node is identified as this context. 

Given that, the expression .[1] is always the same as just "." alone. it simply always selects the current context element. 

If the current context element is from an array element declaration, then imagine that the absolute path expression for the array element is /root/bar where bar is an array element. Suppose the current array index is 3. 

In that case, the expression ".[1]" behaves like the absolute path "/root/bar[3]", which behaves the same as "/root/bar[dfdl:occursIndex()]".

".[1]" in DFDL expressions always means the same thing as just "." because the context node is always a single element occurrence, and never denotes an entire array which could be indexed into with any index position other than 1.

**Comment by smhdfdl** [comment]
@mbeckerle looking at the XPath 2.0 spec I see the following statements:

- "the self axis contains just the context node itself"
- "If the value of the predicate expression is a [singleton](https://www.w3.org/TR/xpath20/#dt-singleton) atomic value of a [numeric](https://www.w3.org/TR/xpath20/#dt-numeric) type or derived from a [numeric](https://www.w3.org/TR/xpath20/#dt-numeric) type, the predicate truth value is true if the value of the predicate expression is equal (by the eq operator) to the context position, and is false otherwise."

That says to me that for DFDL ".[1]" is the same as "." as we only ever return one node. And that ".[n]" where n <> 1 is an error (an SDE I think?)

**Comment by mbeckerle** [comment]
Agree. I've come around to .[1] is a no-op, and .[2] is an SDE regardless of how the element is declared (scalar or array).

Now, given this schema: 

```
<element name="a" type="int" maxOccurs="unbounded" dfdl:terminator=","/>
<element name="b" type="int" dfdl:terminator=";"/>
<element name="a" type="int" maxOccurs="unbounded" dfdl:terminator=",">
     ... <dfdl:assert> .... ../a[dfdl:occursIndex() - 1] ... </dfdl:assert>
</element>.
```

And data

`1,2,3,4;5,6
`
When parsing the 5, is `dfdl:occursIndex() ` value 1, as it is the first element of the second 'a' array, or is it 4 because if referring to all the 'a' children, that's the fourth 'a' ?

**Comment by smhdfdl** [comment]
From call on 19th Jan 2023.

Revisited the XPath 2.0 specification. Concluded that ".[1]" is the same as "." and that ".[n]" where n <> 1 returns an empty node sequence. Also noted that when using dfdl:occursIndex() in an expression, if any element on the path to the array element has a sibling of the same name, the results of the expression are unpredictable. Also on section 18.5.2.5 the sentence "In the functions below, if the argument includes the current node, or any enclosing parent node, then it is a Schema Definition Error." should be using "evaluates to" not "includes". Mike to update issue #26 with the actual words for the spec (section 18).

**Comment by mbeckerle** [comment]
Specific change language is:

Section 18.4 Notes. Add item number 6 saying: 
The expression ".[1]" is the same as "." and that ".[n]" where n is not equal to 1 returns an empty node sequence.

Section 18.5.2.5 the sentence "In the functions below, if the argument includes the current node, or any enclosing parent node, then it is a Schema Definition Error." should be using "evaluates to" not "includes".

**Comment by mbeckerle** [comment]
Fixed in https://github.com/OpenGridForum/DFDL/pull/45
