### ISSUE TITLE
Simple type used as prefixLengthType with assert or discriminator

### ISSUE THREAD

**Issue by mbeckerle** [OpenGridForum/DFDL#29]
We want to put facet constraints on the numeric value of a prefixLengthType.

This allows superior diagnostics on bad data where the value of a prefix length field is corrupted, or one is simply backtracking through alternatives, and the alternative fails due to the prefix length not making sense. 

A diagnostic to the effect of "prefix length value is not facet valid with respect to maxInclusive 2000." is superior to something like "3928881818 bytes were needed but only 1229 were available". 

So the idea is one could put an assert like this on a xs:simpleType that is used as a dfdl:prefixLengthType:

```<dfdl:assert>{ $someControlingVar or dfdl:checkConstraints(.) }</dfdl:assert>```

So that range checks would apply to a prefix length value before it is used as a length to retrieve/pull data for parsing. 

Sub issues: what path expressions are allowed? Possibly only "." because anything else could be bound to a variable.

The argument for "." only is that the prefix is not an element attached to the infoset; hence ".." isn't necessarily meaningful.

Absolute paths could however be allowed, but don't need to be as they can be bound to a variable. 

We don't have a use case for other than "." as the path expression. Where the "." refers to the value of the prefix length "quasi-element" itself. This prefix length value is the only thing you don't have a way to reference in an expression. 

One alternative notion is a DFDL function like e.g, dfdl:prefixLength() that returns the value of the prefix length.

Another sub issue is whether the value of "." is before, or after the value is adjusted for the dfdl:prefixIncludesPrefixLength='yes' property. Since the schema author does not have access to the length of the simpleType used for the prefix itself, that suggests the adjustment subtracting away that length, so that "." is the post-adjustment value is the correct choice. 

Another possible annotation on the simpleType that is the prefixLengthType would be setVariable:
```<dfdl:setVariable ref="ex:PrefixLen">{ . }</dfdl:setVariable>```
This would allow capturing the prefixLength's value for use elsewhere in the schema.

**Comment by mbeckerle** [comment]
Sections of the DFDL v1.0 Spec which will require updating include:

- Evaluation Order for Statement Annotations (Section 9.5) - Statements on the prefixLengthType for an element with lengthKind 'prefixed' are evaluated first, before any other annotations. 
- 12.3.4 dfdl:lengthKind 'prefixed' - The definition block for prefixLengthKind needs to specify that the simpleType can have statements, and that these are evaluated before the statements for the element itself. In addition, any DFDL expressions evaluated by such statements can only refer to the quasi-element (holding the value of the prefix length itself) by way of the "." expression. Specifically, the "." does NOT refer to the element having this prefix length, but to the prefix itself. The statement annotations that can be used on a prefixLengthType simpleType are:
-- assert
-- discriminator
-- setVariable
In the material that follows the table in 12.3.4, the sentence "When parsing, the length of the element's content is obtained by parsing the simple type specified by dfdl:prefixLengthType to obtain an integer value." should be modified to insert the word "first" after the word "obtained". A sentence is inserted after this sentence stating: "Any statement annotations on the prefixLengthType are evaluated after the prefix length value is determined, but before the length is used to access or parse any additional data; any parse error that occurs while evaluating such a statement preempts the need to parse any part of the element having that prefixLengthType." 

Furthermore, it must be made clear that the value of "." is the value of the prefix integer, before any subtraction of the length of the prefix itself as per the dfdl:prefixIncludesPrefixLength property. 

In the sentence that discusses unparsing of prefix length, it expresses that the length of the content is computed, then adjusted by prefixIncludesPrefixLength and then can finally be stored/written, followed by the content. 

This must be ammended to make clear that once the new prefix value has been computed, and then adjusted as per prefixIncludesPrefixLength, it is then that any statement annotations (which can only be setVariable, since asserts/discriminators are not evaluated at all at unparse time) are evaluated, and if there is no processing error then the content is written.

**Comment by mbeckerle** [comment]
See PR https://github.com/OpenGridForum/DFDL/pull/33

**Comment by mbeckerle** [comment]
Attached are two files. I had to rename them with ".txt" to get github to accept them. 

One is a schema with a simple prefix-length situation with pattern assert, setVariable, and regular assert annotations on the prefix-prefix length type, the prefix-length type, and the element's type. 

I numbered them with `<!-- Eval N -->` to indicate evaluation order of the annotations. 

The other file is a TDML test file showing what I think this schema does with a small piece of sample data designed to illustrate what all happens, what the variables capture, etc.

**Comment by smhdfdl** [comment]
In passing, identified an undocumented corner case; it is a Processing Error if a prefix-prefix-length type evaluates to 0.

**Comment by mbeckerle** [comment]
The whole prefix-prefix thing comes from an ASN.1 use case. We should find out what ASN.1 does with prefix-prefix if the prefix-prefix value is 0.

**Comment by mbeckerle** [comment]
The ASN.1 BER/DER rules for nested length work in such a way that there is no possible way that the length field itself can be zero length. The length is either 1 byte holding length 0 to 127, or if the MSB is set, then the remaining bits give the length of the length field itself. A byte of 0x80 would mean that the length field itself is length 0, but this value is instead reserved to indicate that a different indefinite length representation is being used. 

So there is no way ASN.1 can have the situation where the length of a length is 0. At least as far as BER/DER are concerned. 

I have not investigated whether ASN.1 ECN can express a different length-encoding scheme where the length of the length can end up being zero or what would happen in that case. 

I think it is prudent for us just to make the conservative decision that when a prefixLength itself has a prefixLengthType, and the length of the length is 0, that it is a parse error, and the minimum length (of a length) when unparsing is 1, not zero.

**Comment by mbeckerle** [comment]
Suggested language changes for the spec:

Section 12.3.4 dfdl:lengthKind 'prefixed'

In the definition of dfdl:prefixLengthType, add this after the bullets about schema definition errors.

If the xs:simpleType is constrained by facets (minInclusive, maxInclusive, minExclusive, maxExclusive)
these constraints are always checked, both when parsing and unparsing. 
It is a processing error if the value of the xs:simpleType does not conform to the facet constraints. 
It is a processing error if the value of the xs:simpleType is less than zero. 

Section 12.3.4.1 Nested Prefix Lengths

Insert the additional sentence

It is a processing error if the nested prefix length value is less than 1.

**Comment by mbeckerle** [comment]
@smhdfdl I have edited a new version of the DFDL spec with all the agreed language errata and all the minor/typo items to date. 

This is the only remaining issue tracker that I believe we wanted to get into this next version. So if you can take a look at the proposed language in the comments above and provide any further suggestions, I can then prepare the revised spec document.

**Comment by smhdfdl** [comment]
The section 12.3.4 property changes look fine.

I don't think section 12.3.4.1 reads well at the moment. I think it should be refactored slightly, see what you think.

_"It is possible for a prefix length, as specified by dfdl:prefixLengthType, to itself have a prefix
length. That is, an element can have a prefix length, which defines a PrefixLength region (see Section 9.2 DFDL Data Syntax Grammar), and the PrefixLength region can itself have a type which specifies a prefix length, thereby
defining a PrefixPrefixLength region. 

It is a Schema Definition Error if the type associated with the PrefixPrefixLength is the same as the type associated with the PrefixLength. It is a Schema Definition Error if a PrefixPrefixLength region has a type which specifies a prefix length, that is, nesting of prefix lengths must not exceed a depth of 1."_

**Comment by mbeckerle** [comment]
The assert, discriminator, or setVariable restriction also applies to any base type thereof.

**Comment by mbeckerle** [comment]
Fixed by https://github.com/OpenGridForum/DFDL/pull/45
