### ISSUE TITLE
Improve description of textNumberPattern 'V' and 'P' symbols (action 331)

### ISSUE THREAD

**Issue by smhdfdl** [OpenGridForum/DFDL#38]
Examination of spec Fig 4 suggests that its poor definition of term `vpinteger` leads to post-figure bullets being needed to clarify what could have been incorporated into the term. Plus some other things noted.

Here's the syntax from Fig 4 ...

```
vpinteger := pinteger | (vinteger exponent?)
pinteger := ('P'* integer) | (integer 'P'* )
vinteger := ('V'? integer) |
            ('#'* 'V'? integer)|
            ('#'* '0'* 'V'? '0'* '0')|
            (integer 'V'?)
integer := '#'* '0'* '0'
```

Here are the bullets ...

• A pattern with a V symbol must not have # symbols to the right of the V symbol.
• A pattern with P symbols at the left end must not have # symbols .
• A pattern with P symbols at the right end can have # symbols.
• A pattern with a V symbol must not have @ or * symbols.
• A pattern with P symbols must not have @ or E or * symbols.

1) I would question why we use 'V'? and 'P'* instead of 'V' and 'P' 'P'*. As written, it allows the V or P to be omitted entirely, but omission is already catered for by the number term (as '.' fraction is optional)

2) If 'V'? becomes 'V' then clause ('#'* 'V'? integer) is invalid as it contradicts bullet 1 as integer allows '#'.

3) Clause ('V'? integer) similarly, but it's redundant anyway as it is implied by the clause in 2)

4) Clause ('P'* integer) can be rewritten as  ('P' 'P'* '0'* 0)  which removes need for bullet 2 

5) Bullets 3, 4 & 5 add nothing.

I think we can rewrite the syntax as below and remove all the bullets.

```
vpinteger := pinteger | (vinteger exponent?)
pinteger := ('P' 'P'* '0'* '0') | (integer 'P'* 'P' )
vinteger := ('#'* '0'* 'V' '0'* '0') | (integer 'V')
```

Note that I have avoided the obvious and more convenient use of 'X'+ because the + qualifier is not used elsewhere in Fig 4, I suspect to avoid confusion with the '+' symbol.  

I would also suggest that the exponent term is incorrect. After checking [ICU DecimalFormat](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4j/com/ibm/icu/text/DecimalFormat.html) and testing with IBM DFDL, the `E` is mandatory so it should be:

```
exponent  := 'E' '+'? '0'* '0'
```

**Comment by smhdfdl** [comment]
[ICU DecimalFormat](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4j/com/ibm/icu/text/DecimalFormat.html) is where we derived our Figure 4 from. It says "_ICU DecimalFormat aims to follow the specification for pattern strings in [UTS #35](http://unicode.org/reports/tr35/tr35-numbers.html#Number_Format_Patterns). Refer to that specification for more information on pattern string syntax._"  There looks to have been some enhancements or clarifications that we might need to incorporate into DFDL 1.0 specification. For example, note minus sign as a symbol, and 'explicit plus' use of plus symbol. We need to do some tests to determine what needs to be updated.

**Comment by mbeckerle** [comment]
Is this allowed in a V pattern: ###V00  ? Or do we require at least one zero the left of the V?

Other than doublechecking that detail, this looks right to me. And greatly cleaned up.

**Comment by smhdfdl** [comment]
@mbeckerle A pattern like ###V00 does not cause an error in IBM DFDL when validating the schema. That makes sense to me, as the pattern is saying to move the dp 2 places to the left and the equivalent explicit dp pattern ##.00 does not cause an error either.

**Comment by mbeckerle** [comment]
Fixed by https://github.com/OpenGridForum/DFDL/pull/45
