### ISSUE TITLE
Improve description of textNumberPattern quote symbol

### ISSUE THREAD

**Issue by smhdfdl** [OpenGridForum/DFDL#39]
The description in Table 17 does not make it clear that quotes can be used to surround multiple characters at a time.

**Comment by smhdfdl** [comment]
Following changes suggested:

1) Paragraph immediately preceding Table 17

"To insert a special character in a pattern as a literal, that is, without any special meaning, the
character, **or a string containing it,** must be **surrounded by quote symbols.**"

2) Quote symbol meaning in Table 17.

"Used to **escape** special characters in a prefix or suffix, for example, "'#'#" formats 123 to "#123". To create a single quote itself, use two in a row: "# o''clock". **Multiple special characters may be escaped either by quoting individually or quoting a containing string, for example "'VALUE' #" and "'V'ALU'E' # both format 123 to "VALUE 123'.**  

3) E symbol and + symbol in Table 17.
"Need not be quoted in prefix or suffix** if use is unambiguous**".

**Comment by mbeckerle** [comment]
+1 looks correct.

**Comment by mbeckerle** [comment]
Fixed by https://github.com/OpenGridForum/DFDL/pull/45
